// Shared copy for the in-game rulebook and the public rules page.
export const RULES = [
  {
    id: 'measurement', title: 'Superposition', legacy: 'Quantum Pieces & Superposition',
    concept: 'Movement is measurement',
    summary: 'Every piece begins in a superposition of Pawn, Knight, Bishop, Rook, Queen and King.',
    paragraphs: ['Move as any identity still present. The move projects the piece onto the identities compatible with that displacement.', 'A knight leap resolves a piece as Knight. A clear diagonal move of two or more squares preserves Bishop and Queen.'],
    detail: 'White moves first; turns alternate. Paths, captures and pawn direction follow the movement rules of each remaining identity. Pawns may occupy the back rank. A possible Pawn can double-step from either of its two home ranks when the path is clear; this does not depend on whether the piece has moved before.',
    action: 'Measure a diagonal move', before: [{ label: 'Initial state', types: 'pnbrqk' }], after: [{ label: 'Diagonal projection', types: 'bq' }],
    caption: 'Only Bishop and Queen are compatible with a clear diagonal displacement of two or more squares.',
  },
  {
    id: 'zap', title: 'Zap', legacy: 'The Zap', concept: 'Zap as partial measurement',
    summary: 'Think of Zap as a partial measurement: enemy contact rules out one identity while leaving the piece on the board, often with several possibilities still open.',
    paragraphs: ['After movement, the piece projects contact from its lowest-value remaining identity. Contact follows capture geometry. The order is Pawn → Knight → Bishop → Rook → Queen → King.', 'Enemy contact attempts to remove the highest-value identity: King first, then Queen, Rook, Bishop, Knight and Pawn. The remaining joint state must satisfy the census.'],
    detail: 'All zaps resolve as one volley. When removals conflict, retain the largest admissible set, then prefer higher-value identities and earlier squares in algebraic order. If the volley would remove every remaining King possibility, affected targets retry below King. A zap can propagate census collapse to pieces outside the contact geometry.',
    action: 'Apply enemy contact', before: [{ label: 'Target', types: 'pnbrqk' }], after: [{ label: 'King removed', types: 'pnbrq' }],
    caption: 'Here King can be removed: another King possibility remains, and the census admits the new state.',
  },
  {
    id: 'heal', title: 'Heal', legacy: 'The Heal', concept: 'Heal as state preparation',
    summary: 'Think of Heal as state preparation through a friendly interaction: it adds a missing identity back into the piece’s superposition, opening another possible way to move.',
    paragraphs: ['A heal restores a missing identity that the joint census permits, starting with the lowest value.', 'Several heals may support one another. They resolve jointly, restoring as many contacted pieces as possible.'],
    detail: 'The usual order is Pawn, Knight, Bishop, Rook, Queen, King; equal-size healing combinations prefer lower-value regains in board order. If a side has no King possibility, King is attempted first. Pawn cannot return to a promoted piece or a piece on its promotion rank. No admissible regain means the state remains unchanged.',
    action: 'Apply friendly contact', before: [{ label: 'Before contact', types: 'bq' }], after: [{ label: 'Pawn restored', types: 'pbq' }],
    caption: 'This example assumes a King possibility remains and the census permits Pawn to return.',
  },
  {
    id: 'census', title: 'Census', legacy: 'The Census (Conservation)', concept: 'The state belongs to the whole army',
    summary: 'Every admissible state must contain one complete chess set per side.',
    paragraphs: ['The conserved slots are 8 Pawns, 2 Knights, 2 Bishops, 2 Rooks, 1 Queen and 1 King. Captured pieces still occupy their slots.', 'When one superposition changes, the census removes identities that no longer fit elsewhere. This is a collapse cascade: a distant piece can resolve without being contacted.'],
    detail: 'Two resolved Knights exclude Knight from every other unpromoted piece on that side. Constraints can also arise from groups: three Bishop–Queen pieces occupy both Bishop slots and the Queen slot. A closed group does not provide an automatic shield against a zap.',
    action: 'Zap King from d5', before: [{ label: 'd5 · contact', types: 'rk' }, { label: 'e8 · distant', types: 'qk' }, { label: 'a8 · distant', types: 'rq' }], after: [{ label: 'd5 · Rook', types: 'r' }, { label: 'e8 · King', types: 'k' }, { label: 'a8 · Queen', types: 'q' }],
    caption: 'Only one Rook, one Queen and one King slot remain. Removing King at d5 determines all three pieces.',
  },
  {
    id: 'capture', title: 'Capture', legacy: 'Captures', concept: 'A captured state becomes definite',
    summary: 'Capture resolves the victim as its lowest-value remaining identity.',
    paragraphs: ['A Knight–Queen superposition is captured as Knight. The resolved identity remains in the census after the piece leaves the board.', 'Resolution proceeds in order: movement → capture → census → contact. The capturing piece then zaps enemies and heals friends from its landing square.'],
    detail: 'The capture order is Pawn, Knight, Bishop, Rook, Queen, King. Capturing a superposition that includes King does not by itself win the game. Victory requires checkmate of a revealed King.',
    action: 'Resolve the capture', before: [{ label: 'Victim', types: 'nq' }], after: [{ label: 'Captured · still counted', types: 'n' }], caption: 'Knight is the lowest-value identity present in the captured superposition.',
  },
  {
    id: 'royal', title: 'King & shield', legacy: 'Winning: Checkmate', concept: 'Royal possibility is conserved by Zap',
    summary: 'Zap cannot remove the final King possibility. Check applies only to a revealed King.',
    paragraphs: ['A revealed King has exactly one identity: King. It cannot be left capturable. Checkmate ends the game.', 'A gold shield marks a contact that removes nothing: the state is already definite, or no removal preserves the census and royal safeguard.'],
    detail: 'If a target is the final King-or-Queen superposition, Zap attempts Queen instead of King. A shield appears only if no admissible removal remains. If another resolution leaves a side temporarily without a King possibility, play continues; a later heal can restore King.',
    action: 'Zap the final royal state', before: [{ label: 'Only King possibility', types: 'qk' }], after: [{ label: 'Queen removed · King preserved', types: 'k' }], caption: 'The royal safeguard redirects this zap to Queen. A subsequent zap of the definite King produces a shield.',
  },
  {
    id: 'castle', title: 'Castling', legacy: 'Castling (Rook–King Pairing)', concept: 'A joint Rook–King projection',
    summary: 'Once per game, select two back-rank superpositions that each contain both Rook and King.',
    paragraphs: ['Click one eligible piece, then the other. The interval between them must be clear and contain at least one empty square.', 'The pieces form a central adjacent pair and project onto Rook–King. The census then constrains the joint state.'],
    detail: 'Previous movement does not remove eligibility. With only one empty square between the pieces, one starting square is retained. Castling never captures and consumes the turn. It must respect the census and cannot leave a revealed King capturable. Later contact can heal the castled pieces normally.',
  },
  {
    id: 'enpassant', title: 'En passant', legacy: 'En Passant (Phantom Capture)', concept: 'A joint Pawn measurement',
    summary: 'A possible Pawn that double-steps opens an en passant window for one turn.',
    paragraphs: ['An adjacent possible Pawn may capture diagonally into the crossed square. The double-stepping piece is removed from its landing square.', 'Both pieces project onto Pawn. The capturer then makes contact from its new square.'],
    detail: 'The double-step begins on either of the mover’s two home ranks, along a clear file. The capturer must be beside the arrival square, and the crossed square must be empty. If an ordinary move to that square is also legal, choose whether to perform the en passant measurement.',
  },
  {
    id: 'promotion', title: 'Promotion', legacy: 'Quantum Promotion', concept: 'The Pawn branch transforms',
    summary: 'At the farthest rank, a Pawn branch becomes a superposition of Knight, Bishop, Rook and Queen.',
    paragraphs: ['Other identity branches remain. Each promotion-derived identity still occupies a Pawn census slot.', 'The bar under a promoted piece marks this branch. Promotion occurs once per piece; healing cannot restore Pawn afterward.'],
    detail: 'Promotion-derived branches remain constrained by the Pawn pool. If all eight Pawn slots are claimed elsewhere, those branches are excluded. On capture, the piece resolves as its lowest-value remaining identity while retaining its census origin.',
    action: 'Reach the promotion rank', before: [{ label: 'Pawn branch', types: 'p' }], after: [{ label: 'One Pawn census slot', types: 'nbrq' }], caption: 'The displayed identity changes; its census origin remains Pawn.',
  },
  {
    id: 'draw', title: 'Draws', legacy: 'Draws', concept: 'When the position stops evolving',
    summary: 'Stalemate, threefold repetition and the fifty-move rule produce a draw.',
    paragraphs: ['Stalemate means no legal move when the side to move is not in check. Repetition compares the full quantum state, including the side to move and en passant window.', 'The fifty-move clock resets on a capture, a definite Pawn move, promotion, or a net reduction of possibilities across the board.'],
    detail: 'The limit is 100 half-moves without one of those changes. Repetition also includes promotion branches and castling state. A heal alone does not reset the clock. Players may agree a draw or resign.',
  },
];
