// frontend/src/puzzle/puzzleQuotes.js
// Purpose: 365 chess×physics mashup quotes — one per day, rotating with the
// daily puzzle. Classic chess aphorisms bent through physics wordplay. Every
// byline is a FICTIONAL punny mashup of a chess player and/or scientist;
// nothing here is presented as a real quote from a real person.
// Imports From: None
// Exported To: ./MinedPuzzleModal.jsx (quote of the day on the done card)

export const PUZZLE_QUOTES = [
  { q: 'When you see a good move, look for a better one — but know that measuring the first changes the second.', by: 'Werner Lasker' },
  { q: 'The blunders are all there on the board, waiting to be observed.', by: 'Savielly Dirac' },
  { q: 'The winner is the player who makes the next-to-last measurement.', by: 'Savielly Dirac' },
  { q: 'Before the endgame, the gods placed the middlegame. Before the middlegame, a wave function.', by: 'Isaac Steinitz' },
  { q: 'Every chess master was once a superposition of all possible beginners.', by: 'Rudolf Einstein' },
  { q: 'A knight on the rim is dim; a knight in two places is physics.', by: 'Erwin Fischer' },
  { q: 'Passed pawns must be pushed — an object in motion stays in motion.', by: 'Isaac Steinitz' },
  { q: 'The threat is stronger than the execution, and the wave is stronger than the particle.', by: 'Boris Bohr' },
  { q: 'I don’t believe in psychology. I believe in good eigenstates.', by: 'Erwin Fischer' },
  { q: 'Take your opponent into a deep dark forest where two plus two equals five and light bends.', by: 'Nikola Tal' },
  { q: 'A pawn is the soul of chess, and the soul, it turns out, is quantized.', by: 'Max Alekhine' },
  { q: 'Help your pieces so they can help you: action, reaction.', by: 'Isaac Steinitz' },
  { q: 'The hardest game to win is a won game — entropy never rests.', by: 'Enrico Capablanca' },
  { q: 'Even a poor plan is better than no plan; even a collapsed wave function beats no wave at all.', by: 'Cecilia Chigorin' },
  { q: 'Tactics flow from a superior position the way heat flows from hot to cold: always, and only that way.', by: 'Enrico Capablanca' },
  { q: 'Play the opening like a book, the middlegame like a magician, and the endgame like a Turing machine.', by: 'Tigran Turing' },
  { q: 'Attack! Always attack — every force deserves an equal and opposite one.', by: 'Isaac Steinitz' },
  { q: 'The King is a fighting piece. Use it — mass is just frozen energy.', by: 'Rudolf Einstein' },
  { q: 'A win by an unsound combination fills me with artistic horror and the vacuum with virtual particles.', by: 'Akiba Oppenheimer' },
  { q: 'The beauty of a move lies not in its appearance but in the equation behind it.', by: 'Savielly Dirac' },
  { q: 'One bad move nullifies forty good ones. Physicists call this symmetry breaking.', by: 'Emmy Menchik' },
  { q: 'Chess, like love, like music, has the power to make time dilate.', by: 'Rudolf Einstein' },
  { q: 'I see only one move ahead, but it is always the most probable amplitude.', by: 'Enrico Capablanca' },
  { q: 'Study the endgame first: every system tends toward its ground state.', by: 'Enrico Capablanca' },
  { q: 'The passed pawn is a criminal that must be kept under observation — unobserved, it is everywhere at once.', by: 'Wolfgang Nimzowitsch' },
  { q: 'First restrain, then blockade, finally collapse the wave function.', by: 'Wolfgang Nimzowitsch' },
  { q: 'Even the laziest king flees wildly from a double check — spooky action at short distance.', by: 'Wolfgang Nimzowitsch' },
  { q: 'Never move a pawn and you will never lose a game; never observe the board and it stays a draw forever.', by: 'Erwin Fischer' },
  { q: 'All rook endgames are drawn. All isolated systems approach equilibrium. Same theorem.', by: 'Enrico Capablanca' },
  { q: 'Long analysis, wrong analysis: past three half-lives nothing of the plan remains.', by: 'Marie Lane' },
  { q: 'When you don’t know what to do, wait for your opponent to get an idea. It is sure to decay.', by: 'Savielly Dirac' },
  { q: 'An isolated pawn spreads gloom over the board like dark energy over the cosmos.', by: 'Vera Graf' },
  { q: 'Some part of every mistake is correct — call it wave-particle duality.', by: 'Boris Bohr' },
  { q: 'Moral victories don’t count. Neither do virtual particles, until they do.', by: 'Savielly Dirac' },
  { q: 'It is always better to sacrifice your opponent’s pieces. Conservation laws say nothing against it.', by: 'Emmy Menchik' },
  { q: 'A game is always won through a mistake — usually a measurement made too early.', by: 'Werner Lasker' },
  { q: 'The pin is mightier than the sword, and the strong force is mightier than the pin.', by: 'Ernest Smyslov' },
  { q: 'God does not play dice, but He clearly plays chess with the pieces face down.', by: 'Rudolf Einstein' },
  { q: 'To play the queen too early is to spend all your energy in the first instant — ask any Big Bang.', by: 'Cecilia Chigorin' },
  { q: 'The knight’s move is proof that nature permits tunneling.', by: 'David Feynman' },
  { q: 'What I cannot checkmate, I do not understand.', by: 'David Feynman' },
  { q: 'You can observe the position or you can keep your plan. Never both.', by: 'Werner Lasker' },
  { q: 'A sacrifice is best refuted by accepting it — every particle meets its antiparticle eventually.', by: 'Savielly Dirac' },
  { q: 'My opponent’s king is both castled and lost until I look.', by: 'Erwin Fischer' },
  { q: 'If you cannot explain your combination to a pawn, you do not understand it yourself.', by: 'David Feynman' },
  { q: 'The center is not a place. It is a field.', by: 'Efim Faraday' },
  { q: 'Whoever sees the whole board at once has stopped time; be suspicious of them.', by: 'Rudolf Einstein' },
  { q: 'A bad bishop guards good pawns the way a black hole guards its information: technically.', by: 'Stephen Reti' },
  { q: 'Do not develop hopes before knights. Nothing exceeds the speed of getting your pieces out.', by: 'Rudolf Einstein' },
  { q: 'The opening is a boundary condition. Play it accordingly.', by: 'Savielly Dirac' },
  { q: 'In a bad position, remember: the universe began in a worse one.', by: 'Cecilia Chigorin' },
  { q: 'Chess is the struggle against error, which is to say, against entropy, which is to say, against time.', by: 'Werner Lasker' },
  { q: 'Every pawn is a potential queen — every particle, a potential universe. Promote responsibly.', by: 'Max Alekhine' },
  { q: 'Nothing clarifies a position like a capture; nothing collapses a wave like a detector.', by: 'Boris Bohr' },
  { q: 'Two bishops sweep the board like crossed fields: perpendicular, and better together.', by: 'James Euwe' },
  { q: 'He who fears an isolated queen’s pawn should give up chess, and he who fears uncertainty should give up knowing.', by: 'Werner Lasker' },
  { q: 'The mistake is always on the board, superposed with the brilliancy. Your move is the measurement.', by: 'Boris Bohr' },
  { q: 'Openings teach you openings. Endgames teach you thermodynamics.', by: 'Enrico Capablanca' },
  { q: 'A plan without calculation is a theory without an experiment.', by: 'Ernest Smyslov' },
  { q: 'I will make forty good moves, and if the universe makes forty perfect ones, the draw conserves us both.', by: 'Ernest Smyslov' },
  { q: 'Castle early: symmetry, once broken, cannot be repaired — only compensated.', by: 'Emmy Menchik' },
  { q: 'The double-slit taught us everything: a pawn that can take two ways attacks through both until you choose.', by: 'Boris Bohr' },
  { q: 'A knight fork is entanglement with consequences.', by: 'Nikola Tal' },
  { q: 'Do not calculate every variation. Sum over the histories that matter.', by: 'David Feynman' },
  { q: 'Between the opening and the endgame, the gods have placed decoherence.', by: 'Erwin Fischer' },
  { q: 'The board is eight by eight, but the game is infinite-dimensional.', by: 'Stephen Reti' },
  { q: 'To improve at chess, first accept that the observer is part of the position.', by: 'Boris Bohr' },
  { q: 'Zugzwang: the only force in nature that acts on a body at rest.', by: 'Isaac Steinitz' },
  { q: 'My pieces vibrate with possibility. Yours merely stand there, classical.', by: 'Nikola Tal' },
  { q: 'The rook belongs behind the passed pawn — every wave needs a source.', by: 'Efim Faraday' },
  { q: 'A queen sacrifice is a supernova: catastrophic locally, illuminating everywhere else.', by: 'Cecilia Chigorin' },
  { q: 'Time trouble is relativity you can feel: five minutes for you, an hour for your opponent.', by: 'Rudolf Einstein' },
  { q: 'Every exchange radiates a little heat. By the endgame, the board is cold enough to see clearly.', by: 'Enrico Capablanca' },
  { q: 'You cannot step on the same square twice; the position has already changed.', by: 'Boris Bohr' },
  { q: 'Weak squares are curvature: pieces fall into them without being pushed.', by: 'Rudolf Einstein' },
  { q: 'A knight outpost is a bound state. Dislodging it costs more energy than it looks.', by: 'Max Alekhine' },
  { q: 'Whoever controls the long diagonal controls a geodesic.', by: 'Stephen Reti' },
  { q: 'The initiative is momentum. You may trade it for position, but never simply lose it.', by: 'Emmy Menchik' },
  { q: 'Every Russian schoolboy knows the second law: material advantages must be converted before they dissipate.', by: 'Ernest Smyslov' },
  { q: 'Nothing is more dangerous than a passed pawn at escape velocity.', by: 'Isaac Steinitz' },
  { q: 'Simplify when ahead: fewer bodies, fewer problems. Ask anyone who has tried three.', by: 'Enrico Capablanca' },
  { q: 'The bishop pair is interference done right: two waves, one crushing amplitude.', by: 'James Euwe' },
  { q: 'A tempo is a quantum of initiative. It cannot be subdivided, only wasted whole.', by: 'Max Alekhine' },
  { q: 'Prophylaxis: measuring your opponent’s idea before it exists.', by: 'Wolfgang Nimzowitsch' },
  { q: 'The elegant variation and the sound one rarely commute.', by: 'Savielly Dirac' },
  { q: 'Chess is ninety-nine percent tactics, and tactics are ninety-nine percent empty space.', by: 'Ernest Smyslov' },
  { q: 'Play with a plan: even light travels in straight lines until the position curves.', by: 'Rudolf Einstein' },
  { q: 'The worst bishop still outshines the best excuse — luminosity is not the same as usefulness.', by: 'Cecilia Chigorin' },
  { q: 'Do not fear ghosts on the board. Fear the ones your detector confirms.', by: 'Erwin Fischer' },
  { q: 'A cramped position contains its own escape, the way a nucleus contains its alpha particle. Wait for the tunnel.', by: 'Marie Lane' },
  { q: 'Chess is mental torture, and torture, properly measured, is just work done against the mind.', by: 'Garry Kelvinov' },
  { q: 'If you’re not winning, you’re learning; if you’re not learning, you’re a closed system.', by: 'Magnus Carnot' },
  { q: 'I am the strongest player in any reference frame moving with me.', by: 'Magnus Carnot' },
  { q: 'Some sacrifices are sound; the rest are merely irreversible.', by: 'Mikhail Thermodynamikhail' },
  { q: 'Attack the king, not the clock — though both only run one way.', by: 'Garry Kelvinov' },
  { q: 'Every move creates a weakness. Every emission leaves a recoil. Move anyway.', by: 'Judit Perturbár' },
  { q: 'Play the board, not the man; measure the state, not the physicist.', by: 'Bobby Fissioner' },
  { q: 'My favorite piece is whichever one the wave function says I meant to move.', by: 'Hikaru Nakamuon' },
  { q: 'Blitz is chess at relativistic speed: your clock runs slow only from your own side of the board.', by: 'Hikaru Nakamuon' },
  { q: 'Show me a player without weaknesses and I will show you a system at absolute zero: perfect, and unable to move.', by: 'Garry Kelvinov' },
  { q: 'The best defense is a good offense; the best offense is a gauge symmetry nobody noticed.', by: 'Emmy Menchik' },
  { q: 'You need not play the best move, only a move your opponent’s model of you has already ruled out.', by: 'Tigran Turing' },
  { q: 'Losing a won game hurts twice: once in this branch, and once in every world where you converted.', by: 'Hugh Everettovich' },
  { q: 'Resigning is a measurement too. Postpone it.', by: 'Erwin Fischer' },
  { q: 'The half-open file is a slit: put a rook through it and watch the interference pattern on the seventh.', by: 'Boris Bohr' },
  { q: 'Doubled pawns are degenerate states: same energy, worse structure.', by: 'Wolfgang Nimzowitsch' },
  { q: 'A miniature is a particle collision: brief, violent, and the detector prints something beautiful.', by: 'Nikola Tal' },
  { q: 'Trust your preparation until move ten; after that, trust conservation laws.', by: 'Emmy Menchik' },
  { q: 'The fianchetto is a telescope: one small aperture, the whole sky of the long diagonal.', by: 'Galileo Greco' },
  { q: 'And yet the pawn moves.', by: 'Galileo Greco' },
  { q: 'I dropped a bishop and a rook from the same height, and they lost with equal acceleration.', by: 'Galileo Greco' },
  { q: 'Perpetual check is the only perpetual motion machine the laws permit.', by: 'Mikhail Thermodynamikhail' },
  { q: 'Stalemate: proof that zero energy is still a state.', by: 'Savielly Dirac' },
  { q: 'The en passant rule is a boundary condition — ignore it and your solution diverges on move one.', by: 'James Euwe' },
  { q: 'Grab development, not pawns: potential energy beats rest mass in the opening.', by: 'Max Alekhine' },
  { q: 'The exchange sacrifice buys field strength with material. Faraday would have taken the knight too.', by: 'Efim Faraday' },
  { q: 'Your opponent also has the right to exist, as matter tolerates antimatter: briefly, and at a distance.', by: 'Savielly Dirac' },
  { q: 'A well-timed zap removes the king from a piece the way ionization removes an electron: cleanly, and forever.', by: 'Marie Lane' },
  { q: 'Heal your back rank. Even the vacuum repairs itself.', by: 'David Feynman' },
  { q: 'A shielded piece is a noble gas: full shell, no reaction, insufferably stable.', by: 'Marie Lane' },
  { q: 'The census is Noether’s theorem with a chess set: every symmetry of the army is a law you cannot break.', by: 'Emmy Menchik' },
  { q: 'Count your maybe-kings the way you count significant figures: pessimistically.', by: 'Enrico Capablanca' },
  { q: 'In quantum chess as in cosmology: most of the army is dark, and you infer it from how the rest moves.', by: 'Vera Graf' },
  { q: 'Never trade your good bishop for a photon of counterplay.', by: 'Ernest Smyslov' },
  { q: 'The clock is the only piece that captures both players.', by: 'Rudolf Einstein' },
  { q: 'Adjust your pieces before the game; calibrate your instruments before the run. J’adoube is good science.', by: 'Ernest Smyslov' },
  { q: 'A threat repeated three times becomes a draw; a result repeated three times becomes a law.', by: 'Isaac Steinitz' },
  { q: 'Underpromotion is choosing the smaller quantum. Sometimes the knight is the only allowed transition.', by: 'Max Alekhine' },
  { q: 'The board never lies, but your basis might.', by: 'Werner Lasker' },
  { q: 'Every gambit is a loan against the vacuum: repay the material before the interest arrives.', by: 'Akiba Oppenheimer' },
  { q: 'Weak players fear the queen. Strong players fear the pawn two ranks from promotion, humming with potential.', by: 'Cecilia Chigorin' },
  { q: 'Ask not whether the move is good. Ask whether it survives renormalization at depth eight.', by: 'David Feynman' },
  { q: 'The back-rank mate is a boundary effect: everything looked fine in the interior.', by: 'Stephen Reti' },
  { q: 'Two weaknesses beat one: no wave was ever canceled by a single slit.', by: 'Boris Bohr' },
  { q: 'A rook lift is a Feynman diagram: sideways in space, forward in intent.', by: 'David Feynman' },
  { q: 'The best move exists whether or not you observe it. Unfortunately, so does the refutation.', by: 'Rudolf Einstein' },
  { q: 'Do not hurry in the endgame: at low temperature, every fluctuation matters.', by: 'Enrico Capablanca' },
  { q: 'Opposite-colored bishops are parallel universes: they pass through the same board and never interact.', by: 'Hugh Everettovich' },
  { q: 'A premature attack radiates away its energy and leaves a cold, losing structure. See: every star, eventually.', by: 'Cecilia Chigorin' },
  { q: 'Learn openings by principle, not by rote — nature memorizes no ephemeris either, it just obeys gravity.', by: 'Isaac Steinitz' },
  { q: 'The pawn storm obeys fluid dynamics: easy to start, impossible to recall.', by: 'James Euwe' },
  { q: 'Where the knights go first, the field follows.', by: 'Efim Faraday' },
  { q: 'Chess is a closed system, which is why your advantage, unconverted, becomes heat.', by: 'Mikhail Thermodynamikhail' },
  { q: 'Every combination begins with an unstable nucleus: a loose piece, an open king, a half-life measured in moves.', by: 'Marie Lane' },
  { q: 'Respect material like you respect mass-energy: it converts, but the receipt is always itemized.', by: 'Rudolf Einstein' },
  { q: 'Their engine says minus two. My detector says the experiment is not over.', by: 'Hikaru Nakamuon' },
  { q: 'An attack on the wing is answered in the center, as every field line eventually returns.', by: 'Efim Faraday' },
  { q: 'A knight on d5 is worth a theory of everything on a1.', by: 'Ernest Smyslov' },
  { q: 'Exchange into won endgames the way excited atoms shed photons: gladly, and down the energy ladder.', by: 'Max Alekhine' },
  { q: 'The best players see the same board and a different Hamiltonian.', by: 'Savielly Dirac' },
  { q: 'Beware quiet moves: the strong force is short-ranged and silent until you are inside it.', by: 'Ernest Smyslov' },
  { q: 'A passed pawn’s value grows as it advances. So does a rocket’s. Both are mostly fuel.', by: 'Isaac Steinitz' },
  { q: 'The best time to resign is never; the second-best time is after the heat death of the position.', by: 'Mikhail Thermodynamikhail' },
  { q: 'The king in the endgame is a phase transition: the same piece, suddenly liquid.', by: 'Enrico Capablanca' },
  { q: 'Fortune favors the prepared position.', by: 'Louis Pastukhov' },
  { q: 'Somewhere, something incredible is waiting to be checkmated.', by: 'Carl Sagalkin' },
  { q: 'We are all made of star stuff, but your rook is made of my former pawn. Promotion is nucleosynthesis.', by: 'Carl Sagalkin' },
  { q: 'Extraordinary sacrifices require extraordinary compensation.', by: 'Carl Sagalkin' },
  { q: 'The cosmos is within us — and so, apparently, was that mate in three.', by: 'Carl Sagalkin' },
  { q: 'If I have seen further into this position, it is by standing on the shoulders of my doubled pawns.', by: 'Isaac Steinitz' },
  { q: 'A combination releases its energy only after the position reaches critical mass.', by: 'Lise Meitnervinnik' },
  { q: 'The failed variation is still data. Record it before repeating the experiment.', by: 'Lise Meitnervinnik' },
  { q: 'Imagination is more important than preparation — preparation ends at move twelve.', by: 'Rudolf Einstein' },
  { q: 'Insanity is repeating the same opening and expecting a different middlegame.', by: 'Rudolf Einstein' },
  { q: 'Everything should be made as simple as possible, but not one exchange simpler.', by: 'Rudolf Einstein' },
  { q: 'The universe is under no obligation to make your pet line make sense.', by: 'Neil deGrasse Tysonovich' },
  { q: 'The good thing about the evaluation bar is that it’s true whether or not you believe in it.', by: 'Neil deGrasse Tysonovich' },
  { q: 'The shortest route to the king is rarely a straight line; calculate the orbit first.', by: 'Katherine Johnsonchuk' },
  { q: 'Check the trajectory twice. A single missing square can lose the whole mission.', by: 'Katherine Johnsonchuk' },
  { q: 'Not only does God play dice with the opening, He sometimes castles where we cannot see.', by: 'Stephen Reti' },
  { q: 'However bad the position, there is always something you can do and succeed at. Where there is check, there is hope.', by: 'Stephen Reti' },
  { q: 'Black holes are not so black, and lost positions are not so lost.', by: 'Stephen Reti' },
  { q: 'Intelligence is the ability to adapt to a changed move order.', by: 'Stephen Reti' },
  { q: 'The eval was not lowered to zero. It tunneled there.', by: 'Werner Lasker' },
  { q: 'Shut up and calculate.', by: 'Mikhail Botmermin' },
  { q: 'If you think you understand this position, you do not understand this position.', by: 'David Feynman' },
  { q: 'Nature isn’t classical, dammit, and if you want to simulate my endgame, you’d better make it quantum.', by: 'David Feynman' },
  { q: 'The first principle of analysis: you must not fool yourself, and your engine is the easiest engine to fool.', by: 'David Feynman' },
  { q: 'For every attack there is an equal and opposite counterattack — delayed by exactly one tempo.', by: 'Isaac Steinitz' },
  { q: 'An apple fell on my head and I finally understood: the h-pawn was hanging the whole time.', by: 'Isaac Steinitz' },
  { q: 'E equals mc²: Evaluation equals material times coordination squared.', by: 'Rudolf Einstein' },
  { q: 'Time and space are one fabric. So are tempo and squares. Spend accordingly.', by: 'Rudolf Einstein' },
  { q: 'A watched pot never boils, and a watched flag never falls on the first time control.', by: 'Erwin Fischer' },
  { q: 'My cat is simultaneously winning and losing this position. Do not open the tablebase.', by: 'Erwin Fischer' },
  { q: 'I refuted my own opening once. Twice, counting the world where I played it anyway.', by: 'Hugh Everettovich' },
  { q: 'Somewhere in the multiverse you took the draw. This is not that universe.', by: 'Hugh Everettovich' },
  { q: 'Every branching line is real. Grief for the missed win is just amplitude leaking between worlds.', by: 'Hugh Everettovich' },
  { q: 'Give me a lever long enough and a firm outpost on which to place it, and I shall move the whole queenside.', by: 'Archimedes Philidorou' },
  { q: 'Eureka! The bath overflowed, and so does the e-file once the rooks double.', by: 'Archimedes Philidorou' },
  { q: 'Do not disturb my endgame circles.', by: 'Archimedes Philidorou' },
  { q: 'Pawns are the fulcrum of chess. Everything heavier balances on them.', by: 'Archimedes Philidorou' },
  { q: 'Knowledge of the opening is power; knowledge of the ending is torque.', by: 'Francis Bacallero' },
  { q: 'It moves in mysterious rays.', by: 'Marie Lane' },
  { q: 'Nothing in chess is to be feared, only understood. Now is the time to understand more, so that we may blunder less.', by: 'Marie Lane' },
  { q: 'Be less curious about ratings and more curious about positions.', by: 'Marie Lane' },
  { q: 'A brilliancy glows for a night. A principle glows for a career. Half-lives vary.', by: 'Marie Lane' },
  { q: 'God made the initial position; all else is the work of man.', by: 'Leopold Kroneckstein' },
  { q: 'I think, therefore I am lost in thought on move nineteen.', by: 'René Descartekower' },
  { q: 'Cogito ergo zugzwang: I think, therefore any move I make weakens something.', by: 'René Descartekower' },
  { q: 'A move is a hypothesis; the reply is the experiment that decides whether it survives.', by: 'David Feynman' },
  { q: 'Calculation begins where certainty ends and the candidate moves start interfering.', by: 'Boris Bohr' },
  { q: 'The board rewards economy: one useful piece can do the work of three ornamental ones.', by: 'Enrico Capablanca' },
  { q: 'When two plans branch from one position, prepare for the world in which your opponent finds both.', by: 'Hugh Everettovich' },
  { q: 'Every loose piece has a half-life. Attack it before the clock reaches zero.', by: 'Marie Lane' },
  { q: 'A knight in superposition forks possibilities before it ever forks pieces.', by: 'Erwin Fischer' },
  { q: 'Development is potential energy; leave it on the back rank and it performs no work.', by: 'Isaac Steinitz' },
  { q: 'The initiative is conserved only by spending it. A waiting move radiates some away.', by: 'Emmy Menchik' },
  { q: 'A closed file is not empty; it is a field waiting for the right pawn break.', by: 'Efim Faraday' },
  { q: 'The best defense changes the geometry of the attack before the attackers arrive.', by: 'Ernest Smyslov' },
  { q: 'Your opponent’s uncertainty is a resource. Do not collapse it for free.', by: 'Werner Lasker' },
  { q: 'A sacrifice without follow-up is energy released where no instrument can detect it.', by: 'Akiba Oppenheimer' },
  { q: 'The center curves every route across the board; control it and distant pieces arrive sooner.', by: 'Rudolf Einstein' },
  { q: 'A passed pawn is a small star: harmless at a distance, decisive near collapse.', by: 'Cecilia Chigorin' },
  { q: 'The queen is strongest when the smaller pieces have already measured the danger.', by: 'Nikola Tal' },
  { q: 'A quiet move can have zero noise and maximum amplitude.', by: 'Savielly Dirac' },
  { q: 'Before calculating deeper, ask whether you are solving the right position.', by: 'Tigran Turing' },
  { q: 'A blockade turns the pawn’s momentum into pressure on the rest of its army.', by: 'Wolfgang Nimzowitsch' },
  { q: 'A tempo is indivisible: spend the whole quantum or lose the whole quantum.', by: 'Max Alekhine' },
  { q: 'Good endgame technique removes variables until only the winning equation remains.', by: 'James Euwe' },
  { q: 'If your plan cannot survive one forcing reply, it was an observation, not a theory.', by: 'Vera Graf' },
  { q: 'A rook on an open file is a telescope aimed directly at the seventh rank.', by: 'Galileo Greco' },
  { q: 'Every exchange cools the position; know whether your advantage survives at low temperature.', by: 'Mikhail Thermodynamikhail' },
  { q: 'The evaluation may be constant while the practical pressure accelerates.', by: 'Garry Kelvinov' },
  { q: 'Speed helps only after pattern recognition has chosen the right branch.', by: 'Hikaru Nakamuon' },
  { q: 'The strongest move is the one that remains strongest in every useful reference frame.', by: 'Magnus Carnot' },
  { q: 'A tactic is not a surprise once every defender has been counted.', by: 'Judit Perturbár' },
  { q: 'Even a classical pawn can become quantum trouble when nobody calculates its promotion square.', by: 'Bobby Fissioner' },
  { q: 'A position becomes simple only after you understand which complications do not matter.', by: 'Enrico Capablanca' },
  { q: 'Checks are measurements with immediate peer review.', by: 'David Feynman' },
  { q: 'A pin fixes one coordinate while leaving the rest of the position uncertain.', by: 'Boris Bohr' },
  { q: 'Space is time on a chessboard: more room means your pieces need fewer moves to act.', by: 'Rudolf Einstein' },
  { q: 'The opening stores energy; the middlegame decides where it is released.', by: 'Isaac Steinitz' },
  { q: 'A king behind a shield is stable only until the first missing defender decays.', by: 'Marie Lane' },
  { q: 'Material is conserved in the ledger, not in your comfort.', by: 'Emmy Menchik' },
  { q: 'Every candidate move is an algorithm competing for the same clock cycle.', by: 'Tigran Turing' },
  { q: 'The best outpost changes the value of every nearby square without moving again.', by: 'Max Alekhine' },
  { q: 'A bishop needs an open diagonal the way a current needs a conductor.', by: 'Efim Faraday' },
  { q: 'Endgames expose imprecise units: a single tempo suddenly measures everything.', by: 'Ernest Smyslov' },
  { q: 'A sealed possibility is information made permanent. Spend that certainty carefully.', by: 'Akiba Oppenheimer' },
  { q: 'The board permits many stories, but the legal moves select a basis.', by: 'Savielly Dirac' },
  { q: 'If every line is real, preparation means choosing which worlds deserve your time.', by: 'Hugh Everettovich' },
  { q: 'A shield is not inactivity; it is a failed reaction made visible.', by: 'Marie Lane' },
  { q: 'The census is the symmetry that stops one piece from changing alone.', by: 'Emmy Menchik' },
  { q: 'The fastest attack is the one whose forcing moves reduce your opponent’s choices.', by: 'Hikaru Nakamuon' },
  { q: 'A novelty is useful only if it creates a problem after the memory ends.', by: 'Garry Kelvinov' },
  { q: 'An engine gives a number; a player must still find the path that keeps it.', by: 'Magnus Carnot' },
  { q: 'The hard part of calculation is noticing which defender quietly disappeared.', by: 'Judit Perturbár' },
  { q: 'A pawn does not need certainty about its future to demand attention now.', by: 'Bobby Fissioner' },
  { q: 'You do not win an advantage by owning it; you win by converting it.', by: 'Enrico Capablanca' },
  { q: 'A diagonal is a measurement line drawn through the position.', by: 'Galileo Greco' },
  { q: 'A discovered attack is induction: move one piece and the field appears elsewhere.', by: 'Efim Faraday' },
  { q: 'Zugzwang is a system whose ground state is forbidden by the rules.', by: 'Wolfgang Nimzowitsch' },
  { q: 'A combination is beautiful when every escape loses by a different law.', by: 'Nikola Tal' },
  { q: 'Uncertainty favors the player who can keep more useful answers alive.', by: 'Werner Lasker' },
  { q: 'Promotion is a phase change powered by eight ranks of accumulated pressure.', by: 'Cecilia Chigorin' },
  { q: 'The tablebase is an event horizon: beyond it, opinion cannot escape.', by: 'Stephen Reti' },
  { q: 'A draw is equilibrium, but reaching it may require a violent exchange of energy.', by: 'Mikhail Thermodynamikhail' },
  { q: 'When queens leave the board, small inaccuracies become measurable.', by: 'James Euwe' },
  { q: 'An isolated pawn reveals itself through the pieces forced to orbit it.', by: 'Vera Graf' },
  { q: 'The clock bends every evaluation toward the move you can actually find.', by: 'Rudolf Einstein' },
  { q: 'A best move is an eigenvector: apply the position and its direction remains true.', by: 'Savielly Dirac' },
  { q: 'A blunder is an experiment whose result arrives one move too late.', by: 'David Feynman' },
  { q: 'King Guard turns a forbidden collapse into a visible conservation law.', by: 'Akiba Oppenheimer' },
  { q: 'Healing restores a possibility, but never the time spent losing it.', by: 'Marie Lane' },
  { q: 'Quantum chess rewards the player who can reason before certainty arrives.', by: 'Boris Bohr' },
  { q: 'Win the square first; the piece occupying it is only the current measurement.', by: 'Max Alekhine' },
  { q: 'The knight always jumps twice: once on the board, once in your opponent’s stomach.', by: 'Nikola Tal' },
  { q: 'I can calculate the motion of heavenly bodies, but not the madness of men who push g4.', by: 'Isaac Steinitz' },
  { q: 'Gravity is not responsible for people falling into the Fried Liver.', by: 'Rudolf Einstein' },
  { q: 'The important thing is not to stop sacrificing. Sacrifice has its own reason for existing.', by: 'Rudolf Einstein' },
  { q: 'If the facts don’t fit the opening theory, change the facts over the board.', by: 'Rudolf Einstein' },
  { q: 'Anyone who has never lost on time has never tried anything new in the middlegame.', by: 'Rudolf Einstein' },
  { q: 'The difference between stupidity and genius is that genius knows when to stop calculating.', by: 'Rudolf Einstein' },
  { q: 'An expert is a player who has made all possible blunders in one very narrow opening.', by: 'Boris Bohr' },
  { q: 'Prediction is very difficult, especially about your opponent’s next move.', by: 'Boris Bohr' },
  { q: 'The opposite of a correct move is a wrong move. But the opposite of a profound move may be another profound move.', by: 'Boris Bohr' },
  { q: 'Anyone not shocked by the quantum castle has not understood it.', by: 'Boris Bohr' },
  { q: 'How wonderful that we have met with a refutation. Now we have some hope of making progress.', by: 'Boris Bohr' },
  { q: 'Two pawns are a structure; three pawns are a phase of matter.', by: 'Enrico Capablanca' },
  { q: 'If I cannot estimate the number of piano tuners in Chicago, how shall I estimate your counterplay? Quickly, and to one significant figure.', by: 'Enrico Capablanca' },
  { q: 'A pawn break is fission: split the structure and the energy was always in there, waiting.', by: 'Akiba Oppenheimer' },
  { q: 'Now I am become depth, destroyer of prep.', by: 'Akiba Oppenheimer' },
  { q: 'The optimist invents the attack; the pessimist invents the defense; the realist invents the clock.', by: 'Tigran Turing' },
  { q: 'We can only see a short distance ahead, but we can see plenty there that needs to be done.', by: 'Tigran Turing' },
  { q: 'A move is admissible if no arbiter can distinguish it from a brilliant one in polynomial time.', by: 'Tigran Turing' },
  { q: 'Machines calculate; players decide which infinity to ignore.', by: 'Tigran Turing' },
  { q: 'The pawn chain points at your future. The pawn breaks point at your opponent’s.', by: 'Wolfgang Nimzowitsch' },
  { q: 'Your last move was not even wrong.', by: 'Wolfgang Nimzowitsch' },
  { q: 'No two of my pieces may occupy the same plan. I call it the exclusion principle; you call it coordination.', by: 'Wolfgang Nimzowitsch' },
  { q: 'The blockading piece absorbs the pawn’s momentum and re-emits it as contempt.', by: 'Wolfgang Nimzowitsch' },
  { q: 'A rook on the seventh eats pawns and emits threats: a perfect little reactor.', by: 'Marie Lane' },
  { q: 'In science as in chess, the prize goes not to the first observer but to the one who publishes mate.', by: 'Ernest Smyslov' },
  { q: 'All of chess is either tactics or stamp collecting.', by: 'Ernest Smyslov' },
  { q: 'Fire a pawn at their structure. If it bounces back, you have discovered their nucleus.', by: 'Ernest Smyslov' },
  { q: 'Harmony between the pieces is worth more than the pieces.', by: 'Ernest Smyslov' },
  { q: 'The queen is a laser: coherent, devastating, and useless in fog. Clear your lines first.', by: 'Nikola Tal' },
  { q: 'I do not sacrifice pieces. I lend them to the electromagnetic field.', by: 'Nikola Tal' },
  { q: 'The present is theirs; the endgame, for which I really worked, is mine.', by: 'Nikola Tal' },
  { q: 'Ideas are like knights: it matters less where they stand than where they can land.', by: 'Nikola Tal' },
  { q: 'A discovered check is induction: move the conductor and the current strikes elsewhere.', by: 'Efim Faraday' },
  { q: 'Nothing is too wonderful to be true, if it be consistent with the laws of the census.', by: 'Efim Faraday' },
  { q: 'What use is a newborn pawn? Wait eight ranks and see.', by: 'Efim Faraday' },
  { q: 'The stars are made of hydrogen, helium, and the dreams of pawns on the sixth rank.', by: 'Cecilia Chigorin' },
  { q: 'The most exciting phrase in chess is not “Checkmate!” but “That’s funny, the engine disagrees…”', by: 'David Feynman' },
  { q: 'Chess is like sex: physicists say that about everything.', by: 'David Feynman' },
  { q: 'There’s plenty of room at the bottom of the eval bar.', by: 'David Feynman' },
  { q: 'Study hard what interests you most, in the most undisciplined and original opening possible.', by: 'David Feynman' },
  { q: 'I learned very early the difference between knowing the name of the opening and knowing the opening.', by: 'David Feynman' },
  { q: 'In the space of moves, all pieces are waves. In the space of results, all waves are pieces.', by: 'Savielly Dirac' },
  { q: 'The equation of the position knew about the combination before I did.', by: 'Savielly Dirac' },
  { q: 'Pick a flaw in their structure and be unkind to it mathematically.', by: 'Savielly Dirac' },
  { q: 'Shortest known proof of the existence of antichess: play the same position with the evaluation reversed.', by: 'Savielly Dirac' },
  { q: 'In the beginning there was symmetry. White broke it. Everything since is compensation.', by: 'Emmy Menchik' },
  { q: 'For every conserved quantity there is a symmetry; for every extra tempo, an invariant your opponent forgot.', by: 'Emmy Menchik' },
  { q: 'They told her she could not referee the men’s section. She invented the conservation of dignity.', by: 'Emmy Menchik' },
  { q: 'Space advantage is curvature: your opponent’s pieces travel farther between the same two ideas.', by: 'Stephen Reti' },
  { q: 'My favorite defense begins with the singularity: one knight, no visible support, infinite density of ideas.', by: 'Stephen Reti' },
  { q: 'Information is never destroyed — but in mutual time trouble it is thoroughly scrambled.', by: 'Stephen Reti' },
  { q: 'Quiet moves are quanta: the smallest possible action that still changes everything.', by: 'Max Alekhine' },
  { q: 'A combination is a chain reaction: one loose piece goes critical and the whole kingside follows.', by: 'Max Alekhine' },
  { q: 'I attack in discrete packets. Continuous pressure is a classical illusion.', by: 'Max Alekhine' },
  { q: 'Sit at the board like a photon: no rest frame, all direction.', by: 'Werner Lasker' },
  { q: 'You may know the square or the timing of the breakthrough. Choose wisely.', by: 'Werner Lasker' },
  { q: 'The uncertainty is not in the position. It is in you. This is excellent news for the position.', by: 'Werner Lasker' },
  { q: 'On the chessboard, lies and hypocrisy do not survive renormalization.', by: 'Werner Lasker' },
  { q: 'When the ratio of your calculation to your intuition drops below Planck’s constant, move.', by: 'Max Alekhine' },
  { q: 'The isolated d-pawn is Schrödinger’s weakness: strong and weak until the minor pieces open the box.', by: 'Erwin Fischer' },
  { q: 'I asked the position if it was winning. It asked me to define winning. We settled on a draw.', by: 'Erwin Fischer' },
  { q: 'You cannot unsee a threat, but you can decohere it with a cup of coffee.', by: 'Erwin Fischer' },
  { q: 'The board has sixty-four squares and, at last count, one reality. Use both.', by: 'Erwin Fischer' },
  { q: 'A tempo saved is a tempo earned, compounded at the speed of light.', by: 'Benjamin Franklinstein' },
  { q: 'In this world nothing can be said to be certain, except death, taxes, and the Exchange Slav.', by: 'Benjamin Franklinstein' },
  { q: 'Early to castle and early to trade makes a player healthy, solid, and hard to checkmate.', by: 'Benjamin Franklinstein' },
  { q: 'An ounce of prophylaxis is worth a pound of defense.', by: 'Benjamin Franklinstein' },
  { q: 'Lightning is just the sky playing the Greek Gift.', by: 'Benjamin Franklinstein' },
  { q: 'A drawing mechanism is still a mechanism; isolate it before declaring the experiment failed.', by: 'Lise Meitnervinnik' },
  { q: 'Calculation gives vision a coordinate system.', by: 'Lise Meitnervinnik' },
  { q: 'The three-fold repetition is nature’s way of saying you both proved the same theorem.', by: 'Leopold Kroneckstein' },
  { q: 'A passed pawn increases in strength as the number of pieces on the board diminishes — dark energy in miniature.', by: 'Vera Graf' },
  { q: 'Half the moves in this game are invisible and we deduce them from the rotation of the result.', by: 'Vera Graf' },
  { q: 'Never let them see your preparation curve flatten.', by: 'Vera Graf' },
  { q: 'A prepared novelty is a supercollider: years of tunneling for one nanosecond of new physics.', by: 'Vera Graf' },
  { q: 'The seventh rank is the event horizon: rooks that cross it do not send material back.', by: 'Stephen Reti' },
  { q: 'Their king walked into the center in the middlegame. Some information wants to be destroyed.', by: 'Stephen Reti' },
  { q: 'Grandmasters feel the critical moment the way instruments feel a field: before the needle moves.', by: 'James Euwe' },
  { q: 'Sort your candidate moves like a demon sorts molecules: one gate, no extra work, and the second law files a complaint.', by: 'James Euwe' },
  { q: 'Every open file wants a rook the way every field wants a charge.', by: 'James Euwe' },
  { q: 'Study tactics until the patterns interfere constructively.', by: 'James Euwe' },
  { q: 'The elegance of a mating net lies in its boundary conditions: every flight square, an equation already solved.', by: 'James Euwe' },
  { q: 'Losing my queen taught me general relativity: the board curved, and everything I owned fell toward their rook.', by: 'Galileo Greco' },
  { q: 'Measure what is measurable, and make the king measurable.', by: 'Galileo Greco' },
  { q: 'The traps are written in the language of mathematics. The victims sign in algebraic notation.', by: 'Galileo Greco' },
  { q: 'Doubt is the father of invention and the uncle of the Budapest Gambit.', by: 'Galileo Greco' },
  { q: 'A sound sacrifice is a controlled burn; an unsound one is just arson with witnesses.', by: 'Akiba Oppenheimer' },
  { q: 'Theory ends where your opponent’s memory ends. Physics ends nowhere. Plan for the second case.', by: 'Akiba Oppenheimer' },
  { q: 'In chess, the small stuff is the big stuff wearing a pawn costume.', by: 'Enrico Capablanca' },
  { q: 'Endgame technique is just patience with units attached.', by: 'Enrico Capablanca' },
  { q: 'The universe expands, and so does the meaning of “equal position” after move thirty.', by: 'Cecilia Chigorin' },
  { q: 'We are stardust that learned to castle queenside.', by: 'Cecilia Chigorin' },
  { q: 'Somewhere between the first move and the last, physics quietly becomes poetry. Resign before the poetry.', by: 'Cecilia Chigorin' },
  { q: 'Castling once per game is the Pauli principle for kings: one exemption, no encores.', by: 'Wolfgang Nimzowitsch' },
  { q: 'Every daily puzzle is a double-blind experiment: the position doesn’t know you, and you clearly don’t know the position.', by: 'Boris Bohr' },
  { q: 'Momentum is conserved: whatever your attack loses, your opponent’s counterattack gains.', by: 'Emmy Menchik' },
  { q: 'A grandmaster’s intuition is a trained neural field with a chess set for boundary conditions.', by: 'Tigran Turing' },
  { q: 'The last mistake wins the game; the last measurement writes the history.', by: 'Hugh Everettovich' },
];

// Reorder the authored blocks into a deterministic rotation. Keeping a full
// week between appearances makes the byline feel as fresh as the quote,
// while retaining the same 365-day cycle for everyone.
export const PUZZLE_AUTHOR_COOLDOWN_DAYS = 6;

function buildDailyQuoteRotation(quotes) {
  const buckets = new Map();
  for (const quote of quotes) {
    if (!buckets.has(quote.by)) buckets.set(quote.by, []);
    buckets.get(quote.by).push(quote);
  }

  const rotation = [];
  while (rotation.length < quotes.length) {
    const recentAuthors = new Set(
      rotation.slice(-PUZZLE_AUTHOR_COOLDOWN_DAYS).map((quote) => quote.by)
    );
    let candidates = [...buckets.entries()]
      .filter(([author, remaining]) => remaining.length && !recentAuthors.has(author));

    // Future edits to the pool should never freeze quote selection. This
    // fallback still prevents consecutive repeats; the test suite enforces
    // the stronger cooldown for the curated pool.
    if (!candidates.length) {
      const previousAuthor = rotation[rotation.length - 1]?.by;
      candidates = [...buckets.entries()]
        .filter(([author, remaining]) => remaining.length && author !== previousAuthor);
    }

    candidates.sort((a, b) => (
      b[1].length - a[1].length || a[0].localeCompare(b[0])
    ));
    const [, remaining] = candidates[0];
    rotation.push(remaining.shift());
  }
  return rotation;
}

const DAILY_QUOTE_ROTATION = buildDailyQuoteRotation(PUZZLE_QUOTES);

// Deterministic quote of the day — the same day-number math as
// loadDailyMinedPuzzle (minedPreview.js), so the quote rotates with the
// daily puzzle and is identical for everyone. Returns null for non-date
// strings (dev previews pass '#N').
export function puzzleQuoteForDate(date) {
  const t = new Date(`${date}T00:00:00`).getTime();
  if (!Number.isFinite(t)) return null;
  const dayNumber = Math.floor(t / 86400000);
  const n = DAILY_QUOTE_ROTATION.length;
  return DAILY_QUOTE_ROTATION[((dayNumber % n) + n) % n];
}
