// frontend/src/characters/characterCatalog.js
// Purpose: The playable character roster. Every avatar in public/avatars is a
// character with a tier, a tagline, and one saying per game event. Players
// never type free text — their tagline and sayings are picked from the
// characters they have access to. Tiers: 'starter' (everyone), 'quest'
// (future: unlocked by playing — ids land in profile.unlocked_characters),
// 'premium' (paid tier / tip unlockables).
// Imports From: None
// Exported To: ../sayings/sayingsCatalog.js, ../account/AccountModal.jsx

// Sayings keys match SAYING_EVENTS in ../sayings/sayingsCatalog.js:
// win, loss, draw, capture, collapse. Keep lines under ~60 chars — they
// render in small speech bubbles and one-line tagline slots.

export const CHARACTER_TIERS = ['starter', 'quest', 'premium'];

export const CHARACTERS = [
  // ---------------------------------------------------------- starters —
  // the free roster: ten humans and six living chess pieces.
  {
    id: 'human-01',
    name: 'Nova',
    tier: 'starter',
    image: '/avatars/free/human-01.png',
    tagline: 'Every branch has a bright side.',
    sayings: {
      win: 'See? The bright branch was real.',
      loss: 'Good game — I’ll grow from this one.',
      draw: 'Two suns, one sky. Nice game.',
      capture: 'Borrowing this — forever.',
      collapse: 'All your maybes are done maybe-ing.',
    },
  },
  {
    id: 'human-02',
    name: 'Cass',
    tier: 'starter',
    image: '/avatars/free/human-02.png',
    tagline: 'Reads the board like a night sky.',
    sayings: {
      win: 'The constellations spelled checkmate.',
      loss: 'I misread the stars. Well played.',
      draw: 'Two orbits, never touching.',
      capture: 'One star, plucked from your sky.',
      collapse: 'Your whole sky just turned to daylight.',
    },
  },
  {
    id: 'human-03',
    name: 'Professor Wren',
    tier: 'starter',
    image: '/avatars/free/human-03.png',
    tagline: 'Tenured in tactics, fluent in qubit.',
    sayings: {
      win: 'As the lemma predicted. QED.',
      loss: 'A flaw in my proof — how delightful.',
      draw: 'We must publish jointly, of course.',
      capture: 'Noted, measured, and confiscated.',
      collapse: 'Your position has been peer-reviewed.',
    },
  },
  {
    id: 'human-04',
    name: 'Aurum',
    tier: 'starter',
    image: '/avatars/free/human-04.png',
    tagline: 'Has seen every timeline worth seeing.',
    sayings: {
      win: 'I remember this ending fondly.',
      loss: 'Even old gold tarnishes. Well fought.',
      draw: 'History will call this one a classic.',
      capture: 'Age teaches patience. And timing.',
      collapse: 'Every secret ages into fact.',
    },
  },
  {
    id: 'human-05',
    name: 'Volt',
    tier: 'starter',
    image: '/avatars/free/human-05.png',
    tagline: 'Plays at the speed of thought.',
    sayings: {
      win: 'Zap. Game.',
      loss: 'You out-paced the current. Respect.',
      draw: 'Two live wires, no ground.',
      capture: 'Static? No — kinetic.',
      collapse: 'Full circuit. Every piece lit up.',
    },
  },
  {
    id: 'human-06',
    name: 'Vex',
    tier: 'starter',
    image: '/avatars/free/human-06.png',
    tagline: 'Chaos, but make it fashion.',
    sayings: {
      win: 'Stylish AND correct. Devastating.',
      loss: 'Ugh, fine. The look was still immaculate.',
      draw: 'A tie? In THIS economy?',
      capture: 'That clashes with your position anyway.',
      collapse: 'Transparency is very in this season.',
    },
  },
  {
    id: 'human-07',
    name: 'Comet',
    tier: 'starter',
    image: '/avatars/free/human-07.png',
    tagline: 'Youngest branch on the timeline.',
    sayings: {
      win: 'No way that worked!! GG!',
      loss: 'Whoa. Teach me that one?',
      draw: 'Tie game! Best of three?',
      capture: 'Got one! Mom, look!',
      collapse: 'I can see EVERYTHING. So cool.',
    },
  },
  {
    id: 'human-08',
    name: 'Stillwater',
    tier: 'starter',
    image: '/avatars/free/human-08.png',
    tagline: 'Calm surface. Deep calculation.',
    sayings: {
      win: 'The river arrives. It never hurries.',
      loss: 'You read the depths better. Honor to you.',
      draw: 'Two stones, one stream.',
      capture: 'Taken, like a leaf from the current.',
      collapse: 'The water is clear now. All is seen.',
    },
  },
  {
    id: 'human-09',
    name: 'Lumi',
    tier: 'starter',
    image: '/avatars/free/human-09.png',
    tagline: 'Winning is better with sparkle.',
    sayings: {
      win: 'Confetti time! GG! ✨',
      loss: 'You win this one — dazzling stuff!',
      draw: 'We BOTH sparkle. Acceptable.',
      capture: 'Ooh, shiny. Mine now!',
      collapse: 'Spotlights on! Nowhere to hide!',
    },
  },
  {
    id: 'human-10',
    name: 'Flux',
    tier: 'starter',
    image: '/avatars/free/human-10.png',
    tagline: 'Runs hot and cold — simultaneously.',
    sayings: {
      win: 'Told you both halves of me were winning.',
      loss: 'Half of me saw that coming. Wrong half.',
      draw: 'Hot game, cold result.',
      capture: 'Red or blue, it’s mine in both.',
      collapse: 'No more two-faced pieces. Just facts.',
    },
  },
  {
    id: 'pawn',
    name: 'Pip',
    tier: 'starter',
    image: '/avatars/free/pawn_avatar.png',
    tagline: 'Small piece. Big amplitude.',
    sayings: {
      win: 'Beep! Promotion achieved: winner.',
      loss: 'Recalibrating… gg, friend!',
      draw: 'Split point saved to memory!',
      capture: 'Yoink! *happy beeping*',
      collapse: 'Scan complete. All pieces found!',
    },
  },
  {
    id: 'knight',
    name: 'Onyx',
    tier: 'starter',
    image: '/avatars/free/knight_avatar.png',
    tagline: 'Two forward, one sideways, all mystery.',
    sayings: {
      win: 'The horse you never saw coming.',
      loss: 'Cornered — a rare feat. Well ridden.',
      draw: 'We circle each other forever, then.',
      capture: 'A hoof falls. A piece vanishes.',
      collapse: 'No fog survives the night ride.',
    },
  },
  {
    id: 'bishop',
    name: 'Sanctum',
    tier: 'starter',
    image: '/avatars/free/bishop.png',
    tagline: 'One color of squares. Every color of outcome.',
    sayings: {
      win: 'The diagonal was destiny.',
      loss: 'I strayed from my squares. Blessings on you.',
      draw: 'The scales rest level. So be it.',
      capture: 'Consider it… tithed.',
      collapse: 'All is revealed. Go in peace.',
    },
  },
  {
    id: 'rook',
    name: 'Bastion',
    tier: 'starter',
    image: '/avatars/free/rook_avatar.png',
    tagline: 'The wall that walks.',
    sayings: {
      win: 'The wall advanced. The wall won.',
      loss: 'Even walls fall. Rebuild and return.',
      draw: 'Two fortresses, no siege.',
      capture: 'You knocked. The wall answered.',
      collapse: 'Nothing hides behind rubble.',
    },
  },
  {
    id: 'queen',
    name: 'Vesper',
    tier: 'starter',
    image: '/avatars/free/queen_avatar.png',
    tagline: 'Everywhere at once — even before quantum.',
    sayings: {
      win: 'Every direction was checkmate. I chose one.',
      loss: 'A queen bows only rarely. Savor it.',
      draw: 'Half my board, half of yours.',
      capture: 'You left it in my kingdom. Ergo, mine.',
      collapse: 'My court sees every corner now.',
    },
  },
  {
    id: 'king',
    name: 'Aurelius',
    tier: 'starter',
    image: '/avatars/free/king_avatar.png',
    tagline: 'Heavy is the crown in every branch.',
    sayings: {
      win: 'The crown endures. It always endures.',
      loss: 'A king kneels to skill, never to luck.',
      draw: 'Peace treaties are also victories.',
      capture: 'A royal tax, collected.',
      collapse: 'Rise. There is nothing left to hide.',
    },
  },

  // ---------------------------------------------------------- premium —
  // the collector roster: included in the one-time Premium unlock.
  {
    id: 'astral-samurai-analyst',
    name: 'The Astral Samurai',
    tier: 'premium',
    image: '/avatars/premium/astral-samurai-analyst.png',
    tagline: 'One cut. All timelines.',
    sayings: {
      win: 'The blade fell in every branch at once.',
      loss: 'Your form was flawless. I sheathe my sword.',
      draw: 'Two blades, one stillness.',
      capture: 'Drawn, cut, sheathed.',
      collapse: 'Every shadow on the board is severed.',
    },
  },
  {
    id: 'aurora-hare',
    name: 'Aurora Hare',
    tier: 'premium',
    image: '/avatars/premium/aurora-hare.png',
    tagline: 'Faster than the light it leaves behind.',
    sayings: {
      win: 'You blinked. I won somewhere in there.',
      loss: 'Caught mid-hop! Well sprung.',
      draw: 'We finished in a photo. No photo exists.',
      capture: 'Hopped in, hopped out, plus one.',
      collapse: 'I lapped the board. Saw everything.',
    },
  },
  {
    id: 'celestial-manta',
    name: 'Celestial Manta',
    tier: 'premium',
    image: '/avatars/premium/celestial-manta.png',
    tagline: 'Glides between galaxies and back ranks.',
    sayings: {
      win: 'The tide was always coming in.',
      loss: 'I drifted too far from shore. Well sailed.',
      draw: 'The current carried us both.',
      capture: 'Swallowed by the deep.',
      collapse: 'The whole ocean floor, floodlit.',
    },
  },
  {
    id: 'chrono-automaton',
    name: 'The Chrono-Automaton',
    tier: 'premium',
    image: '/avatars/premium/chrono-automaton.png',
    tagline: 'Wound once, at the dawn of time.',
    sayings: {
      win: 'This outcome was scheduled eons ago.',
      loss: 'A gear slipped. Recorded for maintenance.',
      draw: 'Our mechanisms tick in unison.',
      capture: 'Tick. A piece is subtracted.',
      collapse: 'All springs unwound. All faces read.',
    },
  },
  {
    id: 'cosmic-trickster',
    name: 'The Cosmic Trickster',
    tier: 'premium',
    image: '/avatars/premium/cosmic-trickster.png',
    tagline: 'The punchline is written in starlight.',
    sayings: {
      win: 'And THAT is the punchline. Thank you!',
      loss: 'The joke was on me — rare, delicious.',
      draw: 'A setup with no punchline. Cruel!',
      capture: 'Pick a piece, any piece. Too late!',
      collapse: 'Reveal! The whole trick, explained.',
    },
  },
  {
    id: 'crown-of-many-worlds',
    name: 'The Crown of Many Worlds',
    tier: 'premium',
    image: '/avatars/premium/crown-of-many-worlds.png',
    tagline: 'Worn by every version of the winner.',
    sayings: {
      win: 'In all worlds, the crown returns home.',
      loss: 'In this world alone, I am bested.',
      draw: 'Two heads, one crown, no verdict.',
      capture: 'Annexed by the many-world empire.',
      collapse: 'Every kingdom stands in plain light.',
    },
  },
  {
    id: 'crystal-matador',
    name: 'The Crystal Matador',
    tier: 'premium',
    image: '/avatars/premium/crystal-matador.png',
    tagline: 'Grace under superposition.',
    sayings: {
      win: 'Olé! The final pass, delivered.',
      loss: 'Gored, but gorgeously. Bravo.',
      draw: 'The crowd demands a rematch!',
      capture: 'A flick of the cape — and it’s gone.',
      collapse: 'The arena lights are all on now.',
    },
  },
  {
    id: 'crystal-oracle',
    name: 'The Crystal Oracle',
    tier: 'premium',
    image: '/avatars/premium/crystal-oracle.png',
    tagline: 'Spoilers available on request.',
    sayings: {
      win: 'I foresaw this. I always foresee this.',
      loss: 'The one future I refused to look at.',
      draw: 'I saw two endings. We lived both.',
      capture: 'Prophecy fulfilled, piece collected.',
      collapse: 'No futures left — only the present.',
    },
  },
  {
    id: 'cyber-pharaoh',
    name: 'The Cyber-Pharaoh',
    tier: 'premium',
    image: '/avatars/premium/cyber-pharaoh.png',
    tagline: 'Dynasties are just long opening books.',
    sayings: {
      win: 'Another dynasty, another checkmate.',
      loss: 'Entombed! History will avenge me.',
      draw: 'Carve it in the cartouche: equals.',
      capture: 'Tribute, rendered unto the throne.',
      collapse: 'The tomb is opened. All is catalogued.',
    },
  },
  {
    id: 'dark-matter-stag',
    name: 'The Dark Matter Stag',
    tier: 'premium',
    image: '/avatars/premium/dark-matter-stag.png',
    tagline: 'Most of the board is invisible. So am I.',
    sayings: {
      win: 'You only ever saw five percent of me.',
      loss: 'Detected at last. Impressive instruments.',
      draw: 'We passed through each other, unscathed.',
      capture: 'Gravity you can’t explain just took a piece.',
      collapse: 'Strange — being the visible one now.',
    },
  },
  {
    id: 'deep-sea-oracle',
    name: 'The Deep-Sea Oracle',
    tier: 'premium',
    image: '/avatars/premium/deep-sea-oracle.png',
    tagline: 'The pressure down here builds character.',
    sayings: {
      win: 'The abyss votes, and it votes for me.',
      loss: 'Surfaced too fast. The bends, clearly.',
      draw: 'Becalmed, both of us, fathoms down.',
      capture: 'Dragged below. No bubbles.',
      collapse: 'Sonar sweep complete. Nothing hidden.',
    },
  },
  {
    id: 'entangled-jellyfish',
    name: 'The Entangled Jellyfish',
    tier: 'premium',
    image: '/avatars/premium/entangled-jellyfish.png',
    tagline: 'Touch one tentacle, feel it everywhere.',
    sayings: {
      win: 'You tangled with the entangled. GG.',
      loss: 'Untangled, fair and square. Drift on.',
      draw: 'Knotted together till the tide turns.',
      capture: 'Sting first, apologize never.',
      collapse: 'Every tendril accounted for.',
    },
  },
  {
    id: 'event-horizon-owl',
    name: 'The Event Horizon Owl',
    tier: 'premium',
    image: '/avatars/premium/event-horizon-owl.png',
    tagline: 'Sees past the point of no return.',
    sayings: {
      win: 'Hoo? You. Past the horizon, no exit.',
      loss: 'Something escaped my gravity. Noted.',
      draw: 'We orbit the same silence.',
      capture: 'Crossed my horizon. Kept forever.',
      collapse: 'Nothing escapes — especially secrets.',
    },
  },
  {
    id: 'glitch-trickster',
    name: 'The Glitch Trickster',
    tier: 'premium',
    image: '/avatars/premium/glitch-trickster.png',
    tagline: 'Not a bug. A lifestyle.',
    sayings: {
      win: 'gg n0 re — the glitch was the plan.',
      loss: 'Patched at last. Respect the dev.',
      draw: 'Result corrupted. Both saves kept.',
      capture: 'Item duplication? No. Item deletion.',
      collapse: 'Wallhacks legalized. I see it all.',
    },
  },
  {
    id: 'inferno-blacksmith',
    name: 'The Inferno Blacksmith',
    tier: 'premium',
    image: '/avatars/premium/inferno-blacksmith.png',
    tagline: 'Forges wins while they’re hot.',
    sayings: {
      win: 'Quenched. The blade holds its edge.',
      loss: 'Back to the forge with me. Fine work.',
      draw: 'Two hammers, one anvil, no verdict.',
      capture: 'Into the furnace it goes.',
      collapse: 'White-hot and fully visible.',
    },
  },
  {
    id: 'lunar-street-racer',
    name: 'The Lunar Street Racer',
    tier: 'premium',
    image: '/avatars/premium/lunar-street-racer.png',
    tagline: 'Low gravity, lower lap times.',
    sayings: {
      win: 'Checkered flag! Photo finish not required.',
      loss: 'Spun out on the last corner. Clean race.',
      draw: 'Dead heat on the dark side.',
      capture: 'Sorry — no brakes on move night.',
      collapse: 'High beams on. Whole track visible.',
    },
  },
  {
    id: 'moonlit-tiger',
    name: 'The Moonlit Tiger',
    tier: 'premium',
    image: '/avatars/premium/moonlit-tiger.png',
    tagline: 'Stripes are just probability bands.',
    sayings: {
      win: 'The pounce lands once. Once is enough.',
      loss: 'Out-stalked in my own jungle. Rare.',
      draw: 'Two predators, mutual respect.',
      capture: 'Silent paws. Missing piece.',
      collapse: 'Moonlight on everything. Hunt’s over.',
    },
  },
  {
    id: 'neon-phoenix',
    name: 'The Neon Phoenix',
    tier: 'premium',
    image: '/avatars/premium/neon-phoenix.png',
    tagline: 'Losses are just pre-wins.',
    sayings: {
      win: 'Risen, again. Ashes make great openings.',
      loss: 'Burn me down — I return brighter.',
      draw: 'Embers on both sides of the board.',
      capture: 'Touched the flame. Paid the piece.',
      collapse: 'Everything glows in firelight.',
    },
  },
  {
    id: 'neon-pirate-captain',
    name: 'The Neon Pirate Captain',
    tier: 'premium',
    image: '/avatars/premium/neon-pirate-captain.png',
    tagline: 'Sails the probability seas for plunder.',
    sayings: {
      win: 'Yo ho — the board be MY treasure now.',
      loss: 'Scuttled! Ye fought like a kraken.',
      draw: 'Split the loot, split the point.',
      capture: 'Plundered, fair and pirate-square.',
      collapse: 'X marks EVERY spot now, matey.',
    },
  },
  {
    id: 'plasma-serpent',
    name: 'The Plasma Serpent',
    tier: 'premium',
    image: '/avatars/premium/plasma-serpent.png',
    tagline: 'Coils measured in kelvin.',
    sayings: {
      win: 'Constriction complete. Sleep well.',
      loss: 'Shed that game like old skin. Onward.',
      draw: 'Coiled, uncoiled, and even.',
      capture: 'One strike. One fewer piece.',
      collapse: 'Infrared vision: everything warm is seen.',
    },
  },
  {
    id: 'quantum-fox',
    name: 'The Quantum Fox',
    tier: 'premium',
    image: '/avatars/premium/quantum-fox.png',
    tagline: 'Sly in nine tails and nine timelines.',
    sayings: {
      win: 'Outfoxed in every universe at once.',
      loss: 'The fox bows — the hound was cleverer.',
      draw: 'Two sly grins, no henhouse.',
      capture: 'The henhouse thanks you for the donation.',
      collapse: 'No burrow left unlit.',
    },
  },
  {
    id: 'quantum-jazz-sorcerer',
    name: 'The Quantum Jazz Sorcerer',
    tier: 'premium',
    image: '/avatars/premium/quantum-jazz-sorcerer.png',
    tagline: 'Improvises in keys that don’t exist yet.',
    sayings: {
      win: 'That final chord? Checkmate in B-flat.',
      loss: 'You played the changes better. Encore.',
      draw: 'We resolved to the same note. Wild.',
      capture: 'Took your piece on the off-beat.',
      collapse: 'Every voice in the mix, soloed.',
    },
  },
  {
    id: 'rogue-astrophysicist',
    name: 'The Rogue Astrophysicist',
    tier: 'premium',
    image: '/avatars/premium/rogue-astrophysicist.png',
    tagline: 'Peer review couldn’t hold me.',
    sayings: {
      win: 'Hypothesis confirmed: you lose. p < .001.',
      loss: 'Fascinating — a result I can’t replicate.',
      draw: 'Inconclusive. Further funding required.',
      capture: 'Sample collected. For science.',
      collapse: 'Full-sky survey complete. No dark data.',
    },
  },
  {
    id: 'schrodingers-cat',
    name: 'Schrödinger’s Cat',
    tier: 'premium',
    image: '/avatars/premium/schrodingers-cat.png',
    tagline: 'Alive, well, and winning. Probably.',
    sayings: {
      win: 'Open the box. It’s a win. It was always a win.',
      loss: 'In the other box, I won. Trust me.',
      draw: 'The box stays closed. Both of us are right.',
      capture: 'Curiosity captured the piece.',
      collapse: 'Everyone’s box is open now. Awkward.',
    },
  },
  {
    id: 'singularity-golem',
    name: 'The Singularity Golem',
    tier: 'premium',
    image: '/avatars/premium/singularity-golem.png',
    tagline: 'Density: yes.',
    sayings: {
      win: 'RESULT: INEVITABLE. GG, SMALL PIECES.',
      loss: 'ERROR: DEFEAT. LOGGED. RESPECT: EARNED.',
      draw: 'EQUILIBRIUM ACHIEVED. ACCEPTABLE.',
      capture: 'ABSORBED. MASS INCREASED.',
      collapse: 'ALL DATA COMPRESSED TO CERTAINTY.',
    },
  },
  {
    id: 'solar-nomad-princess',
    name: 'The Solar Nomad Princess',
    tier: 'premium',
    image: '/avatars/premium/solar-nomad-princess.png',
    tagline: 'Home is wherever the light lands.',
    sayings: {
      win: 'The caravan moves on, one crown richer.',
      loss: 'The dunes shift. So shall I. Well played.',
      draw: 'We share the oasis tonight.',
      capture: 'The desert keeps what it takes.',
      collapse: 'High noon — no shadows anywhere.',
    },
  },
  {
    id: 'space-cowboy-gambler',
    name: 'The Space Cowboy',
    tier: 'premium',
    image: '/avatars/premium/space-cowboy-gambler.png',
    tagline: 'Bets the ranch on the branch.',
    sayings: {
      win: 'Read your bluff from three star systems out.',
      loss: 'You cleaned me out, partner. Tip o’ the hat.',
      draw: 'Push. Nobody draws down.',
      capture: 'I’ll take that pot — and that piece.',
      collapse: 'Cards on the table. ALL of ’em.',
    },
  },
  {
    id: 'starship-botanist',
    name: 'The Starship Botanist',
    tier: 'premium',
    image: '/avatars/premium/starship-botanist.png',
    tagline: 'Grows openings in zero-g.',
    sayings: {
      win: 'Harvest time. The seedling was checkmate.',
      loss: 'Pruned! I’ll grow back — I always do.',
      draw: 'Two gardens, one greenhouse.',
      capture: 'Weeded. The board looks healthier.',
      collapse: 'Grow lights on full. Every root exposed.',
    },
  },
  {
    id: 'thunder-monk',
    name: 'The Thunder Monk',
    tier: 'premium',
    image: '/avatars/premium/thunder-monk.png',
    tagline: 'Silence, then the storm.',
    sayings: {
      win: 'The thunder you heard was inevitability.',
      loss: 'I am humbled. The storm passes through me.',
      draw: 'Two storms, one mountain, no victor.',
      capture: 'Struck. Precisely once.',
      collapse: 'Lightning shows the whole valley.',
    },
  },
  {
    id: 'time-traveling-rastafarian',
    name: 'The Timestream Wanderer',
    tier: 'premium',
    image: '/avatars/premium/time-traveling-rastafarian.png',
    tagline: 'Everything irie, in every era.',
    sayings: {
      win: 'Told you tomorrow already — I win today.',
      loss: 'This timeline’s yours, friend. Respect.',
      draw: 'Past, present, future — all balanced.',
      capture: 'That piece? Already gone yesterday.',
      collapse: 'Every moment visible, all at once. Irie.',
    },
  },
  {
    id: 'void-viking-queen',
    name: 'The Void Viking Queen',
    tier: 'premium',
    image: '/avatars/premium/void-viking-queen.png',
    tagline: 'Raids the fjords between universes.',
    sayings: {
      win: 'The saga ends as all my sagas end. Skål!',
      loss: 'A worthy saga — sing it loudly.',
      draw: 'The runes read: neither yields.',
      capture: 'Raided. The longship rides lower now.',
      collapse: 'The mists part. Valhalla sees all.',
    },
  },
  {
    id: 'void-wolf',
    name: 'The Void Wolf',
    tier: 'premium',
    image: '/avatars/premium/void-wolf.png',
    tagline: 'Howls in frequencies the board can feel.',
    sayings: {
      win: 'The pack sends its regards.',
      loss: 'A stronger howl tonight. I remember it.',
      draw: 'We circle, neither bares the throat.',
      capture: 'The void feeds.',
      collapse: 'Nothing left to stalk. All is seen.',
    },
  },
];

const BY_ID = new Map(CHARACTERS.map((c) => [c.id, c]));

export function getCharacterById(id) {
  return BY_ID.get(id) || null;
}

// The characters a player can pick taglines/sayings from. Starters are
// always in; quest characters need their id in unlockedIds (future:
// profile.unlocked_characters); premium needs the paid tier.
export function unlockedCharacters({ isPaid = false, unlockedIds = [] } = {}) {
  const unlocked = new Set(unlockedIds);
  return CHARACTERS.filter((c) =>
    c.tier === 'starter'
    || (c.tier === 'quest' && unlocked.has(c.id))
    || (c.tier === 'premium' && isPaid)
  );
}

export default CHARACTERS;